stages:
  - style

include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  stage: style
  allow_failure: true
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]
  rules:
    - if: '$CODE_QUALITY_DISABLED'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"' # Run code quality job in merge request pipelines
#    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'      # Run code quality job in pipelines on the default branch (but not in other branch pipelines)
    - if: '$CI_COMMIT_BRANCH'                            # Run code quality job in pipelines on all branches
    - if: '$CI_COMMIT_TAG'                               # Run code quality job in pipelines for tags

