version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: hello_aws_django
    ports:
      - 8000:8000

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    image: hello_aws_nuxt
    depends_on:
      - api
    ports:
      - 3000:3000
