name: Python

on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:

env:
  WORKDIR: api

jobs:
  lint:
    uses: WITH-Test/workflows/.github/workflows/lint-python.yml@main
    with:
      project-folder: ${{ env.WORKDIR }}
      DEPENDENCY_MANAGER: 'poetry'

  build-image:
    needs: lint
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    uses: WITH-Test/workflows/.github/workflows/docker-build-push.yml@main
    with:
      project-folder: ${{ env.WORKDIR }}
      container_registry: 'ecr'
      container_repository_uri: '988760979462.dkr.ecr.eu-west-3.amazonaws.com/hello-cicd-api'
