name: Python

on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    uses: WITH-Test/workflows/.github/workflows/lint-python.yml@main
    with:
      project-folder: api
      DEPENDENCY_MANAGER: 'poetry'

  build-image:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    uses: WITH-Test/workflows/.github/workflows/docker-build-push.yml@main
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    with:
      project-folder: api
      container_registry: '988760979462.dkr.ecr.eu-west-3.amazonaws.com'
      container_repository: 'hello-cicd-api'

  select-env:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.doge-env.outputs.environment }}
    steps:
      - name: DogeOps Environment
        id: doge-env
        uses: WITH-Test/action-select-deploy-env@main
        with:
          deploy_unit: api

  deploy:
    runs-on: ubuntu-latest
    needs: select-env
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    uses: WITH-Test/workflows/.github/workflows/dogeops-deploy.yml@main
    environment: ${{ needs.select-env.outputs.environment }}
    with:
      deploy_unit: api
