name: Python

on:
  push:
    paths:
      - "api/**"
  workflow_dispatch:

env:
  runs-on: 'ubuntu-latest'

jobs:
  lint:
    runs-on: ${{ env.runs-on }}
    uses: WITH-Test/workflows/.github/workflows/lint-python.yml@main
    with:
      runs-on: ${{ env.runs-on }}
      project-folder: api
      DEPENDENCY_MANAGER: 'poetry'

  build-image:
    runs-on: ${{ env.runs-on }}
    needs: lint
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    uses: WITH-Test/workflows/.github/workflows/docker-build-push.yml@main
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    with:
      project-folder: api
      container_registry: '988760979462.dkr.ecr.eu-west-3.amazonaws.com'
      container_repository: 'hello-cicd-api'

  deploy:
    runs-on: ${{ env.runs-on }}
    needs: build-image
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    uses: WITH-Test/workflows/.github/workflows/dogeops-deploy.yml@main
    with:
      deploy_unit: api
